{{- if not .Values.useLegacyProvisioner }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: pd.csi.storage.gke.io
parameters:
  type: {{ .Values.volumeClassName }}
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  name: default
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
{{- end }}
